// Generated by ts-to-zod
import { z } from 'zod'

const variableObjSchema = z.object({
  VarId: z.number().min(1),
  variableName: z.string().min(1),
  type: z.string().min(1),
})

const functionObjSchema = z.object({
  FuncId: z.number().min(1),
  functionName: z.string().min(1),
  type: z.string().min(1),
})

const formObjectTypeSchema = z.union([functionObjSchema, variableObjSchema]).nullable()

const classNodeDataSchema = z.object({
  className: z.string().max(8),
  variables: z.array(variableObjSchema),
  functions: z.array(functionObjSchema),
})

export {
  classNodeDataSchema
}