// Generated by ts-to-zod
import { z } from 'zod'

const variableObjSchema = z.object({
  VarId: z.number(),
  variableName: z.string(),
  type: z.string(),
})

const functionObjSchema = z.object({
  FuncId: z.number(),
  functionName: z.string(),
  type: z.string(),
})

const formObjectTypeSchema = z.union([functionObjSchema, variableObjSchema]).nullable()

const classNodeDataSchema = z.object({
  className: z.string().min(1),
  variables: z.array(variableObjSchema),
  functions: z.array(functionObjSchema),
})

export { variableObjSchema, functionObjSchema, formObjectTypeSchema, classNodeDataSchema }
